### PR TITLE
Heat Pump Card

### PR DESCRIPTION
**Pull request by juvenalandres**
Initial work on a functional hvac compatible card

### CODE REVIEW

**Comment by juvenalandres** [comment]
This is my first PR ever, so bear with me 😄

**Comment by CM000n** [comment]
All good, no problem. :-)
It looks like out Code Quality Check fails because you have some formatting issues with your code:
```
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing docs/setup/configuration.md
Fixing custom_cards/custom_card_heat_pump/custom_card_heat_pump.yaml

trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing docs/setup/installation.md
Fixing docs/setup/configuration.md
Fixing mkdocs.yml
Fixing custom_cards/custom_card_heat_pump/custom_card_heat_pump.yaml

yamllint.................................................................Failed
- hook id: yamllint
- exit code: 1

Error: cards/custom_card_heat_pump/languages/EN.yaml:1:1: [error] missing document start "---" (document-start)
Error: yml:16:5: [error] wrong indentation: expected 6 but found 4 (indentation)
Error: yml:16:21: [error] string value is not quoted with double quotes (quoted-strings)
Error: yml:17:22: [error] string value is not quoted with double quotes (quoted-strings)
Warning: rds/custom_card_heat_pump/custom_card_heat_pump.yaml:78:15: [warning] comment not indented like content (comments-indentation)
Warning: rds/custom_card_heat_pump/custom_card_heat_pump.yaml:91:15: [warning] comment not indented like content (comments-indentation)
Warning: rds/custom_card_heat_pump/custom_card_heat_pump.yaml:104:15: [warning] comment not indented like content (comments-indentation)
Warning: rds/custom_card_heat_pump/custom_card_heat_pump.yaml:117:15: [warning] comment not indented like content (comments-indentation)
Warning: rds/custom_card_heat_pump/custom_card_heat_pump.yaml:130:15: [warning] comment not indented like content (comments-indentation)
Warning: rds/custom_card_heat_pump/custom_card_heat_pump.yaml:346:4: [warning] missing starting space in comment (comments)
```
Do you need help with that?

**Comment by juvenalandres** [comment]
Yeah, probably a bit of help will speed things up, and I'll learn something.
Regarding the three first errors, I'm not sure what they mean. Did the check correct them automatically?

> Error: yml:16:5: [error] wrong indentation: expected 6 but found 4 (indentation)
Error: yml:16:21: [error] string value is not quoted with double quotes (quoted-strings)
Error: yml:17:22: [error] string value is not quoted with double quotes (quoted-strings)
>
Does the 16:21 refer to the line? Could not find where the double quotes are missing. 
I've removed the commented code as it is no longer needed.

Thanks

**Comment by CM000n** [comment]
We use pre-commit to check certain code standards. You can also install pre-commit locally (only Linux and MacOS) and let it run, then it would check your changes before each commit (as the name suggests) and fix minor errors automatically.

https://pre-commit.com/

Here in the repo it runs via a github-action. The command line output is the same as for a local run, but nothing is automatically fixed here. ;-)


Yes, lines like 16:21 refer to the code line and block. Looks like you fixed most of it in your last change :-)

**Comment by CM000n** [comment]
In Discord we are currently discussing whether to include your card in the standard cards for the custom_repo. If so, we would also need a readme and the .yaml file would have to be stored under the custom_component folder. We would get back to you here. 
Or you are of course welcome to join in on the Discord yourself :-)

**Comment by juvenalandres** [comment]
Can someone give me a hand here. What is failing?

**Comment by CM000n** [comment]
It's probably because you don't have some empty line between text blocks in your README.md. 
Can you run pre-commit locally? Then it should fix the error automatically. 
If not, I will merge anyway, and fix the problem later ;-)

**Pull request merged**
