### PR TITLE
Adjusted custom lock card

### PR DESCRIPTION
**Pull request by 13robin37**
Added the option to only use the card to open a lock.
Also added "jammed" state translation

### CODE REVIEW

**Comment by 13robin37** [comment]
@Gilganik we might want to merge the two lock cards if you're okay with it. Maybe an option to switch between this layout (one button) and your layout (two buttons)? 😊

**Comment by Gilganik** [comment]
> @Gilganik we might want to merge the two lock cards if you're okay with it. Maybe an option to switch between this layout (one button) and your layout (two buttons)? 😊

To me it's fine, what should I do?

**Comment by 13robin37** [comment]
@Gilganik I should have some time in the next few days, will test and open a PR once I merged them.

**Comment by Gilganik** [comment]
> @Gilganik I should have some time in the next few days, will test and open a PR once I merged them. 

Fine for me! I think it will be great

**Review by basbruss — APPROVED** [review]

**Pull request merged**
