### PR TITLE
Create custom_card_irmajavi_entities

### PR DESCRIPTION
**Pull request by irmajavi**
This is a card to show results from the Speedtest.net integration.

### CODE REVIEW

**Comment by r0binj** [comment]
The custom card need to be in a folder and you need docs. 

Please read this: 
[Dev: Custom card](https://ui-lovelace-minimalist.github.io/UI/development/custom_cards/)

**Comment by irmajavi** [comment]
I have waste at least 4 hours of my life trying to upload this code. Everything works in HA. Too much rules in here. This is too complicated forget it.

**Comment by stokkie90** [comment]
> I have waste at least 4 hours of my life trying to upload this code. Everything works in HA. Too much rules in here. This is too complicated forget it.

Happy to help you out tomorrow. It you can reach out to me tomorrow on discord. I won't forget it.

**Comment by basbruss** [comment]
Hi @irmajavi I have converted your files so they pass the pre-commit check. You can find them here:
[custom_card_irmajavi_speedtest.yaml](https://pastebin.com/DAWRJRYS)
[custom_card_irmajavi_entities/readme](https://pastebin.com/rjjApMX6)
[custom_card_irmajavi_entities.yaml](https://pastebin.com/ZWx9wKNy)
Hope this helps a bit. Your cards are very nice!

**Comment by stokkie90** [comment]
@irmajavi problem was Windows (DOS) style line-endings & one indent on a label was not correct. 

```
dos2unix custom_cards/custom_card_irmajavi_entities/custom_card_irmajavi_entities.yaml
```

Tip: Use a editor like vscode. i think it will not use windows style line endings. but i'm not sure (Linux User)

**Comment by irmajavi** [comment]
Im using vscode. What editor can I use on linux? Is there any other step to perform with these cards? I have a few more cards, can I use this pull request to upload the other ones or create a new pull request for every card?

**Comment by stokkie90** [comment]
Nice. Maybe check this site out. and see how your vscode it currenlty set-up: https://qvault.io/clean-code/line-breaks-vs-code-lf-vs-crlf/

**Comment by irmajavi** [comment]
Sorry guys and thank for your help. I am trying to understand all this terminology, fork, pull request, branches, trees.. I been studying some GitHub docs. Again thanks for your help.

**Review by CM000n — APPROVED** [review]

**Pull request merged**
