### PR TITLE
[card_thermostat] Handle high/low temperature, external climate fan, and color for cooling

### PR DESCRIPTION
**Pull request by finder39**
This diff adds three main new features for the `card_thermostat` card:
1. Add the handling of `target_temp_high` & `target_temp_low` for "heat_cool" settings that allow a high/low temperature to be set.
2. Add the ability for fan entity to be given as a variable (used when Nest is added via Homebridge Integration).
3. Color the card icon blue when AC is running (while keeping red for heating) instead of always being red when either is running.

Showing high/low temperature and blue icon when AC is running:
card_themostat_with_high_low

This is a recreation of #587 as I had to have it be from a different branch

### CODE REVIEW

**Comment by finder39** [comment]
@basbruss I only saw one comment on the old pull request, which I commented to the following in response:

image

**Review by schumijo — COMMENTED** [review]
Hi,

I don't have a lot of time to review the code as requested by @basbruss . I thought a 3-row card was already huge but now we have a 4-row card 🤣 (not a criticism)
Seems to be a good job @finder39 
Just one remark I already did in few other PR about color icon. In documentation, guidelines define a red icon for heating and blue icon for on/off device. But this is not really respected in many cards....

**Comment by finder39** [comment]
> Hi,
> 
> I don't have a lot of time to review the code as requested by @basbruss . I thought a 3-row card was already huge but now we have a 4-row card 🤣 (not a criticism) Seems to be a good job @finder39 Just one remark I already did in few other PR about color icon. In documentation, guidelines define a red icon for heating and blue icon for on/off device. But this is not really respected in many cards....

@schumijo 

Personally, I like being able to quickly discern which mode is currently active by the icon color as the "(Heating)/(Cooling)" text kinda blends in to the background and is small. Currently the icon is turned basically grey when off (see attached screenshot).

IMG_F0ABBF463AAF-1


I personally think that having it red while both heating and cooling is strange/confusing, but I'm happy to keep that as the default and make blue for cooling be behind another variable if preferred. Let me know!

**Comment by schumijo** [comment]
> > Hi,
> > I don't have a lot of time to review the code as requested by @basbruss . I thought a 3-row card was already huge but now we have a 4-row card 🤣 (not a criticism) Seems to be a good job @finder39 Just one remark I already did in few other PR about color icon. In documentation, guidelines define a red icon for heating and blue icon for on/off device. But this is not really respected in many cards....
> 
> @schumijo
> 
> Personally, I like being able to quickly discern which mode is currently active by the icon color as the "(Heating)/(Cooling)" text kinda blends in to the background and is small. Currently the icon is turned basically grey when off (see attached screenshot).
> 
> IMG_F0ABBF463AAF-1
> 
> I personally think that having it red while both heating and cooling is strange/confusing, but I'm happy to keep that as the default and make blue for cooling be behind another variable if preferred. Let me know!

@finder39 
You can keep your colored icon for heating/cooling 😉

**Comment by finder39** [comment]
@basbruss let me know if you have any other comments or questions or are good with me landing

**Comment by finder39** [comment]
@basbruss I'm glad you like the changes :)

huh, that shouldn't be happening. Can you send me the template of your sensor when in the mode in that image? (which I think is auto?)

Like this:

Screen Shot 2022-04-12 at 9 53 30 AM

I may need to add some additional logic that understands the difference of the climate entity in `heat_cool` mode and `auto` mode, but will want to see your entity attributes to make sure i'm correctly taking things into account instead of guessing

**Comment by finder39** [comment]
@basbruss please try it now. I correct `target_temp_high`'s `null` check to correctly take `undefined` into account

**Comment by basbruss** [comment]
@finder39 Thanks!

This seems to fix it. I will approve and merge this PR 😃

**Review by basbruss — APPROVED** [review]

**Pull request merged**
