### PR TITLE
Add primary and secondary info vars to card_weather

### PR DESCRIPTION
**Pull request by willyp713**
Adds two new variables for `primary_info` and `secondary_info` for the `custom:simple-weather-card` that is the foundation for this card. More details about these fields is available on the [Simple Weather Card repository](https://github.com/kalkih/simple-weather-card).

This will also need a corresponding change in the `card_weather` documentation to show that these variables are available and how to use them.

### CODE REVIEW

**Comment by CM000n** [comment]
Nice! Can you also adjust the documentation of the card according to your changes?

**Comment by willyp713** [comment]
Actually found a small issue with this. The "default" behavior doesn't seem to work if you choose not to pass through a value for the variable from your UI configuration.

If you _do_ specify a value for either of these variables, then they will show that data correctly.

**Comment by willyp713** [comment]
Ok new minor change; provided initial default values for the two new variables at the top of the file. That appears to fix the default behavior bug.

**Comment by willyp713** [comment]
And lastly merged in the docs updates into this same PR.

**Comment by CM000n** [comment]
Nice! Thank you very much for you work!

**Pull request merged**
