### PR TITLE
Update to fix missing variables

### PR DESCRIPTION
**Pull request by modem158**
1. Changed variables in the name area to strings.  The variables were never set and don't need to exist.
2. Changed the logic in the name area to support graphs less than 1 hour.

### CODE REVIEW

**Comment by Eltarius** [comment]
This PR is not necessary

> 1. Changed variables in the name area to strings.  The variables were never set and don't need to exist.

See https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_damix48_power_details/languages
And https://ui-lovelace-minimalist.github.io/UI/development/custom_cards/ to use language files 😉

**Comment by basbruss** [comment]
Hardcoding in English strings is not recommended and is already provided by translation variables as mentioned by @Eltarius .
Changing the logic seems fine to me.

**Comment by modem158** [comment]
Thanks you two.  I was unaware of how the language files work and a little too eager to contribute.  

Should I just close the pull request?

**Comment by modem158** [comment]
Closing this pull request as I wasn't aware of how the en.yaml languages worked making this update isn't necessary.

**Pull request closed without merging**
