### PR TITLE
Allow custom_card_scenes to also use script

### PR DESCRIPTION
**Pull request by aehru**
Add ability to use this card for more than only scene. If @sildehoop validate the modification of his beautiful card.
Maybe will need to also change card name ?

May be merged with #354 ?

### CODE REVIEW

**Comment by sildehoop** [comment]
Awesome, thank you very much. I will merge is with #354

**Comment by CM000n** [comment]
Hi @aehru, seems thar some of your files have a missing end of line.
Please have a look at the code quality check logs

**Comment by sildehoop** [comment]
> Awesome, thank you very much. I will merge is with #354

This pr can be closed

**Comment by CM000n** [comment]
Closed because it will be merged with #354

**Pull request closed without merging**
