### PR TITLE
Add variables for minSet and maxSet for brightness slider on light card

### PR DESCRIPTION
**Pull request by skrynklarn**
Add variables and option to set a min and max set value for the brightness slider on light card.
This to be able to limit the user to a specific range.

Example
```yaml
cards:
  - type: "custom:button-card"
    template: "card_light"
    entity: light.kitchen_island
    variables:
      ulm_card_light_enable_slider: true
      ulm_card_light_enable_slider_maxSet: 50
```

Build in option in my-slider https://github.com/AnthonMS/my-cards/blob/main/src/my-slider.ts

### CODE REVIEW

**Review by schumijo — CHANGES_REQUESTED** [review]
Code is ok
But you must update documentation with these new variables

**Comment by basbruss** [comment]
@skrynklarn Could you also redirect this PR to the `release` branch as stated in https://github.com/UI-Lovelace-Minimalist/UI/blob/main/.github/CONTRIBUTING.md

**Comment by skrynklarn** [comment]
Update documentation for light card and switched the base branch to `release`

**Review by schumijo — APPROVED** [review]
Approved. Good job 👍

**Pull request merged**
