### PR TITLE
Custom name (issue #778)

### PR DESCRIPTION
**Pull request by schumijo**
PR to solve issue #778 

Done :
- card_battery : Variable `ulm_card_battery_name` added

### CODE REVIEW

**Comment by basbruss** [comment]
@schumijo Can we also add a variable for the label and icon for those affected by the new framework?

**Comment by schumijo** [comment]
@basbruss : yes we can

**Comment by basbruss** [comment]
Added to:

`card_binary_sensor` and `card_binary_sensor_alert`
- name variable: `ulm_card_binary_sensor_(alert_)name`
- icon variable: `ulm_card_binary_sensor_(alert_)icon`
- Translation engine to label

**Comment by schumijo** [comment]
You are too fast @basbruss 🤣
I am trying to work on it between my work meetings but you already did so much things

**Comment by basbruss** [comment]
@schumijo They call it student life 🤣

How are we gonna deal with the custom cards?
Some use internal templates that are adapted to the custom actions framework.
_An idea we can revert internal templates back to the old code and make new ones with a suffix `_new`_

Others use `card_generic_swap` or `card_input_boolean` as templates. I hope they can be changed in the same way as we did to `card_graph`

**Comment by schumijo** [comment]
I don't know 
I think there is 2 different cases :
Custom cards that use nested button-card 
And other ones

**Comment by basbruss** [comment]
@schumijo 
I had some thoughts about it.

The nested ones can be easily converted in the same way this PR does to _official_ cards.

The ones relying on internal templates that have been altered are as you mentioned an other case.
For those, we can set back the internal templates to their old state(legacy). 
We bring the changes to `internal_templates_v2` (example: `icon_info_bg_v2`) and only have to change the template names in the template sections of the official cards.

This prevents us from breaking more custom_cards when there is some new feature. As the custom cards stay unaffected.
Custom_card developers can then choose whether they stay on the old framework or adapt their cards to the framework used in the official cards.

**Comment by schumijo** [comment]
Yes I am agree

**Comment by schumijo** [comment]
@basbruss : Wait ..... I think the changes pushed to icon_info_bg.yaml and icon_more_info.yaml are a mistake. Maybe we could revert to old files. Need some tests.
All changes for custom actions are in icon_more_info_new.yaml

Need some confirmations after reverting to old files
Not totally sure lol

**Comment by basbruss** [comment]
@schumijo 

> Seems not to broke official cards to revert icon_info_bg.yaml and icon_more_info.yaml. Not enough time to test custom cards today.
Custom_cards should also be less broken when reverting back to the old internal templates. None of them have received any updates yet after the v1.0.1 release.
So pure theoretical we can safely revert back to the old internal templates and only need to fix the nested ones 😄

**Comment by schumijo** [comment]
I did an extract of custom cards that used official templates which have been changed for custom actions. It means these cards need to be reworked to support new variables :
- custom_card_nik_nas/custom_card_nik_nas.yaml:        template: "card_generic_swap"
- custom_card_nik_nas/custom_card_nik_nas.yaml:        template: "card_generic_swap"
- custom_card_nik_nas/custom_card_nik_nas.yaml:        template: "card_generic_swap"
- custom_card_nik_nas/custom_card_nik_nas.yaml:            template: "card_generic_swap"
- custom_card_vncntdev_device_tracer/vncntdev_card_device_tracer.yaml:  template: "card_generic"
- custom_card_nik_nas/custom_card_nik_nas.yaml:            template: "card_input_boolean"
- custom_card_nik_nas/custom_card_nik_nas.yaml:        template: "card_input_boolean"
- custom_card_nik_tablet/custom_card_nik_tablet.yaml:        template: "card_input_boolean"

**Comment by schumijo** [comment]
I did an extract of custom cards that used official templates which have been changed for custom actions. It means these cards need to be reworked to support new variables :
custom_card_apexcharts/apexcharts.yaml:          - "card_generic_swap"
custom_card_apexcharts/apexcharts.yaml:          - "card_generic_swap"
custom_card_apexcharts/apexcharts.yaml:          - "card_generic_swap"
custom_card_bar_card/custom_card_bar_card.yaml:          - "card_generic"
custom_card_damix48_power_details/custom_card_damix48_power_details.yaml:          - "card_generic"
custom_card_damix48_power_details/custom_card_damix48_power_details.yaml:          - "card_generic"
custom_card_nik_nas/custom_card_nik_nas.yaml:        template: "card_generic_swap"
custom_card_nik_nas/custom_card_nik_nas.yaml:        template: "card_generic_swap"
custom_card_nik_nas/custom_card_nik_nas.yaml:        template: "card_generic_swap"
custom_card_nik_nas/custom_card_nik_nas.yaml:            template: "card_generic_swap"
custom_card_nik_tablet/custom_card_nik_tablet.yaml:          - "card_generic"
custom_card_paddy_dwd_pollen/custom_card_paddy_dwd_pollen.yaml:    - "card_generic_swap"
custom_card_paddy_waste_collection/custom_card_paddy_waste_collection.yaml:    - "card_generic_swap"
custom_card_vncntdev_device_tracer/vncntdev_card_device_tracer.yaml:  template: "card_generic"
custom_card_nik_nas/custom_card_nik_nas.yaml:            template: "card_input_boolean"
custom_card_nik_nas/custom_card_nik_nas.yaml:        template: "card_input_boolean"
custom_card_nik_tablet/custom_card_nik_tablet.yaml:        template: "card_input_boolean"

**Comment by schumijo** [comment]
@basbruss 
I was thinking about the same thing yesterday... And then my child start crying because sleeping was over 🤣🤣

To follow the template, these custom cards need to be rewritten... But I am agree it will be less confusing

**Comment by basbruss** [comment]
@schumijo I think all cards that needed a fix can now change their name and icon with the template we use everywhere in minimalist.
Ready to merge? :smile:

**Comment by schumijo** [comment]
@basbruss : GOOOO 😄

**Review by basbruss — APPROVED** [review]

**Pull request merged**
