### PR TITLE
Restore deleted custom cards

### PR DESCRIPTION
**Pull request by wilbiev**
## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: restore original custom cards deleted with previous pull request
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [X] I have followed the [contribution guidelines](https://github.com/UI-Lovelace-Minimalist/UI/blob/main/.github/CONTRIBUTING.md)
    - [ ] This PR is for a custom-card or documentation change and therefore directed to the `main` branch.
    - [X] This PR is for a official card or any other directly to the integration related change and therefore directed to the `release` branch.

### CODE REVIEW

**Comment by wilbiev** [comment]
@iganeshk can you please review this request? This request restores some custom cards which were accidently deleted in the release repo.

**Comment by wilbiev** [comment]
@warmfire540: please review this PR. With this correction I can sync main with release again. Thanks!

**Review by warmfire540 — APPROVED** [review]
🤷‍♀️ they're back now

**Comment by warmfire540** [comment]
@wilbiev nm - i'm not an approving reviewer... one day 👍

**Comment by KruseLuds** [comment]
What testing is being done on these releases... lol....?

**Comment by wilbiev** [comment]
@KruseLuds good point! There were updated custom cards which I thought I could remove from my PR for repo release. Updated custom cards should be merged with repo main not release. Did not expect they would be actually deleted from the repo. Beginner mistake.

**Review by anya1983 — APPROVED** [review]

**Review by anya1983 — APPROVED** [review]

**Review by anya1983 — APPROVED** [review]
Approved.

**Pull request closed without merging**
