### PR TITLE
Add weather popup

### PR DESCRIPTION
**Pull request by schumijo**
Add weather popup

Translation and doc DONE

### CODE REVIEW

**Comment by matrixx567** [comment]
Hy,

please take a look at my pull request #878. Therefore it won't be necessary to change the `actions_*.yaml` files for every popup and could also improve this popup.

**Comment by schumijo** [comment]
Hi @matrixx567 

Sorry I missed your PR. Sounds interesting to make more cards compatible with popups 👏
It will be a breaking change for users. Maybe we need to see if backward compatibility is possible.

Tell me if I am wrong but it is still necessarry to change action_xxx.yaml to update return entity ?

I will try to integrate your PR in my HA in next days 😉

**Comment by matrixx567** [comment]
Hi @schumijo 

The answer is in the PR #878

**Comment by schumijo** [comment]
Hi @matrixx567 

I need your help :)
I am trying to implement your framework on weather popup from a chip (chip_temperature)
I can't make it working without defining ulm_popup_weather_entity variable.
Is it a normal behaviour ?

```
          - type: 'custom:button-card'
            template: chip_temperature
            entity: weather.maison
            variables:
              ulm_chip_temperature_inside: sensor.outside_temperature
              ulm_chip_temperature_outside: sensor.outside_temperature
              ulm_chip_temperature_weather: weather.maison
              ulm_custom_popup:
                  template: "popup_weather_forecast"
                  popup_variables:
                     ulm_popup_weather_entity: weather.maison
```

**Comment by matrixx567** [comment]
Hi @schumijo 

I think it is a normal behaviour. You are using this variable in your weather popup.

The current custom popups doesn't redirect the entity variable. This has been taken from the original code. I've already tried the redirection of the entity variable but get some errors. I have to take a closer look for using the entity variable within the popups especially if the entity isn't used for the popup.

I will try to implement the feature of using the entity variable within the popups in one of the next releases.

**Comment by schumijo** [comment]
OK thank you @matrixx567 

@basbruss : Ready to merge :)

**Review by basbruss — APPROVED** [review]

**Pull request merged**
