### PR TITLE
Release V1.0.0

### PR DESCRIPTION
**Pull request by basbruss**
Main Features
- Adding a new language engine
- Adding the Adaptive dashboard
- Adding customizable click actions

### CODE REVIEW

**Comment by basbruss** [comment]
@schumijo There are still some commits merged into the `release` branch. If you can try to setup a new PR for the additional needed commits to the most recent updated release branch. Then it should be fine!

**Comment by schumijo** [comment]
@basbruss : OK I am working on your adaptive dashboard integration and will create a new PR later today

**Comment by schumijo** [comment]
@basbruss : I am playing with your adaptive dashboard during my tests... and I can't wait to say : AMAZING !!!!
It is important to read the documentation to understand how to configure but it is absolutely fantastic !!!!!!
FYI : I have added a variable "adaptive" to my custom actions and it works :)

**Comment by basbruss** [comment]
@schumijo Thank you! 😃 

Do you think the documentation is clear enough to get use out of it for most users?

**Comment by schumijo** [comment]
@basbruss : It needs to be read carrefully but yes it is clear enough for me.

**Pull request merged**
