### PR TITLE
Fix custom_action overwrite

### PR DESCRIPTION
**Pull request by schumijo**
Solve #884 and #886

### CODE REVIEW

**Comment by bokub** [comment]
I confirm it solves #886 :tada:

**Comment by schumijo** [comment]
navigate_path are missing
Will add it later....

**Comment by matrixx567** [comment]
Hi @schumijo,

I think the variables can be set in the `icon_more_info_new` and the `icon_more_info_alert` for the custom fields `item1` and `item2`. The template will already set these variables. So there will be no need to change every single card.

**Comment by schumijo** [comment]
Hi @matrixx567 
I already tried this yesterday without success. Is it working on your side ?

**Comment by matrixx567** [comment]
Hi @schumijo ,

I've implemented a working version in my PR #878.
The idea is quite simple. The icon_more_info_new implements the `ulm_custom_actions` template and redirects it to the custom fields.
I've also implement the custom actions on the graph card which uses a generic card as custom field.

Currently I have tested my implementation with the generic_card, graph_card and the power_outlet_card.

Take a look.

**Comment by schumijo** [comment]
Refer to #878

**Pull request closed without merging**
