### PR TITLE
Fix number of forecast entities.

### PR DESCRIPTION
**Pull request by matrixx567**
@schumijo 

This will fix the number of forecast entites described in issue #938

### CODE REVIEW

**Comment by AndyVRD** [comment]
Note that this will push all available attributes forecast low/high temps. So if the entity have more than 6 available it will mess up the layout of the popup. You can see this behaviour/issue with weather.openweathermap.

**Comment by schumijo** [comment]
Yes we need to add a max value in the loop.

**Comment by matrixx567** [comment]
@AndyVRD @schumijo 
already done

**Comment by AndyVRD** [comment]
@matrixx567 Works fine. Will it possible to show the forecast for the next 6 days instead of today + 5 days. I think it don't make allot sense to still show the forecast at the same day?

**Comment by schumijo** [comment]
@AndyVRD @matrixx567 Maybe we could add min and max temp of today on the header and only display next days ?

**Comment by matrixx567** [comment]
@schumijo @AndyVRD 

My first entry is the forecast of tomorrow.
I'm currently implementing a variable for surpressing the first forecast entry.

**Comment by AndyVRD** [comment]
@matrixx567 @schumijo Yeah just fixed it by changing the start index value to 1 and changed the max entree to 6.

**Comment by matrixx567** [comment]
@AndyVRD @schumijo 

I've implemented the variable `ulm_weather_popup_surpress_first_forecast` to surpress the first entry.
It will add a maximum of 6 rows to the card.

**Comment by schumijo** [comment]
Hi @matrixx567 

It is not working on my configuration... and I don't understand why :

```
ButtonCardJSTemplateError: TypeError: Cannot use 'in' operator to search for 'ulm_weather_popup_surpress_first_forecast' in undefined in 'let rows = [];

  function generate_weather_row(index) {
    var row = {
      'type': 'custom:but...'
```

My card configuration : 
```
      - type: "custom:button-card"
        template: chip_temperature
        entity: weather.lieusaint
        variables:
          ulm_chip_temperature_inside: sensor.hue_motion_sensor_1_temperature
          ulm_chip_temperature_outside: sensor.sirene_exterieure_temperature
          ulm_chip_temperature_weather: weather.lieusaint
          ulm_card_weather_enable_popup: true
          ulm_input_select_option: weather
          ulm_input_select: input_select.minimalist_ui_switch
          ulm_weather_popup_surpress_first_forecast: false
```

**Comment by matrixx567** [comment]
@schumijo 

Can you try for-of instead of for-in.

**Comment by AndyVRD** [comment]
> ulm_weather_popup_surpress_first_forecast: false

Needs added like this.

```
        type: "custom:button-card"
        entity: weather.openweathermap
        template:
          - "chip_temperature_mdi_icon"
        variables:
          ulm_weather: "[[[ return variables.ulm_weather]]]"
          ulm_chip_temperature_min: "[[[ return variables.ulm_chip_temperature_min ]]]"
          ulm_chip_temperature_max: "[[[ return variables.ulm_chip_temperature_max ]]]"
          ulm_card_tap_action: "popup"
          ulm_card_tap_haptic: "success"
          ulm_custom_popup:
            template: "popup_weather_forecast"
            popup_variables:
              ulm_popup_weather_entity: "[[[ return variables.ulm_weather]]]"
              ulm_weather_popup_surpress_first_forecast: true
```

**Comment by schumijo** [comment]
> @schumijo
> 
> Do you also use the actions_*.yaml files? There is a change in the return variables. The old version returns a none as variables if they are not set by the user configuration. The version within this PR returns an empty dict.
> 
> You can try following code that checks if the variables are available:
> 
> ```js
>  let surpress_first_forecast = ( variables != null && 'ulm_weather_popup_surpress_first_forecast' in variables) ? variables.ulm_weather_popup_surpress_first_forecast : false;
> ```

**Comment by schumijo** [comment]
@AndyVRD @matrixx567 

I have applied your PR to my configuration.
I will do some more tests with your suggestions.
Still not working with @AndyVRD proposition for now.

**Comment by schumijo** [comment]
To be more precise : I merged all your different PRs

**Comment by AndyVRD** [comment]
@matrixx567 @schumijo Well it works for the large popup but i got the same error as you if i use the mobile popup and navigate to the radar part of the popup. Btw, thanks for the merging, will release some more features and fixes next week.

**Comment by AndyVRD** [comment]
@schumijo Fixed by adding the variable to the popup_weather_radar.yaml.

**Comment by schumijo** [comment]
Well done @AndyVRD 

I confirm it works with these configurations :

```
      - type: "custom:button-card"
        template: chip_temperature
        entity: weather.lieusaint
        variables:
          ulm_chip_temperature_inside: sensor.hue_motion_sensor_1_temperature
          ulm_chip_temperature_outside: sensor.sirene_exterieure_temperature
          ulm_chip_temperature_weather: weather.lieusaint
          ulm_input_select_option: weather
          ulm_input_select: input_select.minimalist_ui_switch
          ulm_custom_popup:
            template: "popup_weather_forecast"
            popup_variables:
              ulm_popup_weather_entity: weather.lieusaint
      - type: "custom:button-card"
        template: chip_temperature
        entity: weather.lieusaint
        variables:
          ulm_chip_temperature_inside: sensor.hue_motion_sensor_1_temperature
          ulm_chip_temperature_outside: sensor.sirene_exterieure_temperature
          ulm_chip_temperature_weather: weather.lieusaint
          ulm_input_select_option: weather
          ulm_input_select: input_select.minimalist_ui_switch
          ulm_card_weather_enable_popup: true
```

**Comment by matrixx567** [comment]
@schumijo 
I think you have to redirect the variables between the popup calls.

**Comment by schumijo** [comment]
> @schumijo I think you have to redirect the variables between the popup calls.

It works fine without

**Comment by basbruss** [comment]
@matrixx567 @schumijo I didn't follow all the conversations and related pr's due to my vacation. But is this PR also ready and needed to merge?

**Comment by schumijo** [comment]
> @matrixx567 @schumijo I didn't follow all the conversations and related pr's due to my vacation. But is this PR also ready and needed to merge?

@basbruss 
I hope you have a good holiday !
Yes this PR is ready

**Review by basbruss — APPROVED** [review]

**Pull request merged**
