### PR TITLE
Custom Person Card + Popup

### PR DESCRIPTION
**Pull request by imswel**
I have created a custom card that improve the `card_person` by allowing the user to set up as many zones as desired and adding a popup for the card inspired by the [@matt8707](https://github.com/matt8707/hass-config)'s theme.

popup

### CODE REVIEW

**Comment by CM000n** [comment]
This looks great @imswel . Thanks a lot!
Have you ever thought about adapting the integrated people card accordingly instead of making a custom component for it?
I think in this case it would fit quite well with the rest of the theme. Maybe @schumijo has an opinion on the popup?

**Comment by schumijo** [comment]
Hi @imswel @CM000n 

Good job. Love the structure of your popup. But I'm not sure it fits the rest of the popup theme with 7ahang's inspiration. Maybe few small tweaks on sensor display and button also are necessary. 
It's just my opinion 😉

**Comment by schumijo** [comment]
And also more important : you should split your card and your popup in specific yaml files

**Comment by CM000n** [comment]
Ok, so we should add it as a custom_card for now, and maybe think about it later if and which features we want to integrate into our standard person card.

**Review by CM000n — APPROVED** [review]

**Review by CM000n — APPROVED** [review]

**Pull request merged**
