### PR TITLE
HACS: Initial Support

### PR DESCRIPTION
**Pull request by stokkie90**
Started on HACS Support, It's work in progress to allow you to follow the progress i made.

### CODE REVIEW

**Comment by bavo** [comment]
Small remark, you’ve committed some personal folders. 

`.vscode` and `.dev-container`

**Comment by tkwy-rick** [comment]
> Small remark, you’ve committed some personal folders.
> 
> `.vscode` and `.dev-container`

This can be used for local development. It's even in the Cookiecutter template for an integration. Other repos have this as well, Example: https://github.com/thomasloven/lovelace-auto-entities

**Comment by httpedo13** [comment]
how much time is need for the first beta?

**Comment by CM000n** [comment]
> how much time is need for the first beta?

That's a bad habit, asking for ETAs 😀

**Comment by CM000n** [comment]
Hi @stokkie90 , have you had a look at my PR yet? https://github.com/stokkie90/UI/pull/3
Because you just made changes to the pre-commit hooks, which I had also already adjusted,

**Pull request merged**
