### PR TITLE
Use entity variable for custom popups.

### PR DESCRIPTION
**Pull request by matrixx567**
Hi @schumijo 

Today I've had some time to mplement the usage of the entity variable for custom popups. Will it be possible to test it with your weather card #894.

As default configuration the entity of the caller card will be used but it can also be overloaded using the entity variable within the ulm_custom_popups configuration.

I've also adapted the internal popups to use the entity variable directly. Therefore the ulm_popup_*_entity variables have been removed.

### CODE REVIEW

**Comment by schumijo** [comment]
Hi @matrixx567 
Test in progress...
Need some rework on weather popup 🤣
Capture

**Comment by matrixx567** [comment]
@schumijo 

A quick fix:

Set the entity within the ulm_custom_popup to none.

**Comment by schumijo** [comment]
> @schumijo
> 
> A quick fix:
> 
> Set the entity within the ulm_custom_popup to none.
> 
> Or set
> 
> Show_name, show_icon, show_label to false

Yes already done, now I lost radar wiew on mobile....

**Comment by schumijo** [comment]
PR for weather popup updated ;)

**Review by basbruss — APPROVED** [review]

**Pull request merged**
