### PR TITLE
Custom printer card with toner status

### PR DESCRIPTION
**Pull request by mp-se**
A custom card to show printer status and toner usage. Based on a post on home assistant forum.

### CODE REVIEW

**Comment by mp-se** [comment]
PLease advice on what the formatting issue is so I can fix it

**Comment by CM000n** [comment]
Hi, you should actually have access to the pre-commit logs of the Github action:
https://github.com/UI-Lovelace-Minimalist/UI/runs/4587461597?check_suite_focus=true#step:4:83

Currently, the main problems are as follows:
- Trailing whitespaces in your readme.md
- Mixed line endings in your custom_card_mpse_printer.yaml
- Missing quoting of string values in your custom_card_mpse_printer.yaml
- Wrong indentation in your custom_card_mpse_printer.yaml

The best thing to do is to install pre-commit locally and run it over your code. Then it should fix most of the problems automatically. The necessary pre-commit configuration is already included in the repo.
https://pre-commit.com/#install

**Comment by mp-se** [comment]
Thanks, I will try that in my fork and do an update of the PR

**Comment by mp-se** [comment]
I cant get pre-commit to work on my windows machine. It cant run the yaml formatter, i dont want to waste more time on that.

**Comment by CM000n** [comment]
Why? It worked after all. All tests passed successfully. Thank you very much :-)

**Comment by mp-se** [comment]
Great it worked. Have some more ideas for cards i want. Love the project.

**Pull request merged**
