### PR TITLE
Update and rename en.json to sl.json

### PR DESCRIPTION
**Pull request by mitchoklemen**
Slovenian translation (Slovenija)

### CODE REVIEW

**Comment by basbruss** [comment]
@mitchoklemen Why are you removing `en.json`? That will get rid of all English string translations for the config UI

**Comment by mitchoklemen** [comment]
Sorry, I meant copy and translate it.

**Comment by basbruss** [comment]
> Sorry, I meant copy and translate it.

Okay, no problem!
Do you want me to add a commit to fix it or will you push a commit?

**Comment by mitchoklemen** [comment]
please add a commit to fix it. tnx

**Review by basbruss — APPROVED** [review]

**Pull request merged**
