### PR TITLE
Card_light Rework color background

### PR DESCRIPTION
**Pull request by basbruss**
Make background colors more inline with examples found on behance

Example with `ulm_card_light_force_background_color: true`
image

Old behavior:
image

- adds variable `ulm_card_light_color` to set manually the color when a light/switch is on

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] I have followed the [contribution guidelines](https://github.com/UI-Lovelace-Minimalist/UI/blob/main/.github/CONTRIBUTING.md)
    - [ ] This PR is for a custom-card or documentation change and therefore directed to the `main` branch.
    - [x] This PR is for a official card or any other directly to the integration related change and therefore directed to the `release` branch.

### CODE REVIEW

**Comment by benbur98** [comment]
Nice work!

I like the white text, it's way more readable than the coloured text previously - I'll check some of the other cards because we might have some inconsistency between cards after this which wouldn't look too good...

For the background, I'm not sure if I prefer the new bold colour in light mode or the old pastel colour personally.
Could make it a variable but aware that the card might get overly complex...

Custom color choice is great too.

**Comment by basbruss** [comment]
By looking at Behance the bold color background for any `active` state is definitely the way to go:
image
@schumijo want to you think on the design changes?

**Review by benbur98 — DISMISSED** [review]
Tested - Card works well :)

**Comment by benbur98** [comment]
image

What is everyones opinion on the colour of the buttons with this forced background? They are not very readable as is. Perhaps they should go white in this mode?

**Comment by benbur98** [comment]
For the Button Colours, what is anyone's opinion on the preferred choice:

Option 1 - Change Icon Only
Option 2 - Set Button Background to White and Icon to the Bard Background Color - this is most similar to the Behance image above
Option 3 - Do Nothing...

image

**Comment by basbruss** [comment]
@benbur98 Oh damn didn't test that feature haha.
Maybe give it the same values as the icon grid?  Same is done with the oscillating button from the card_fan

**Comment by benbur98** [comment]
Sorry there was a bug in that code when not using the Collapse option, also some unnecessary parts.

Please change for:
```
                card:
                  - background-color: >
                      [[[
                        if (!hass.themes.darkMode && variables.mui_card_light_force_background_color) {
                          if (variables.mui_card_light_enable_color && entity.state != "off") {
                            return 'rgba(250, 250, 250,0.8)';
                          }
                        }
                        return 'rgba(var(--color-theme),0.05)';
                      ]]]
                icon:
                  - color: >
                      [[[
                        if (!hass.themes.darkMode && variables.mui_card_light_force_background_color) {
                          if (entity.state != "off") {
                            var color_set = variables.mui_card_light_enable_color ? entity.attributes.rgb_color : variables.mui_card_light_color;
                            var color = 'rgba(var(--color-' + color_set + '),1)';
                            if (variables.mui_card_light_enable_color) {
                              color = 'rgba(' + color_set + ',1)';
                            }
                            return color;
                          }
                        }
                        return 'rgba(var(--color-theme),0.9)';
                      ]]]
```

**Pull request merged**
