### PR TITLE
increase number of colors of the navigation button

### PR DESCRIPTION
**Pull request by auadix**
With this change you can chose from all those available colors (red, pink, purple, deep-purple, indigo, blue, light-blue, cyan, teal, green, light-green, lime, yellow, amber, orange, deep-orange, brown, grey, blue-grey, black, white) instead of being limited to just 6 (blue, red, green, yellow, pink, purple).

### CODE REVIEW

**Comment by auadix** [comment]
Other advantage of this change, the navigation button in the Home Assistant app now show the colors correctly. (tested on Android 13 and iOS 16.2)

**Comment by basbruss** [comment]
Will break configs that have not set a color_value due to absent of a default

**Comment by ABUAIJUTIE** [comment]
Definitely needed! 
It is so weird to limit us in these 6 colors. I mean not only the navigation button, but also the whole UI Minimalist...

**Comment by wilbiev** [comment]
Closing pull request due to lack of activity

**Pull request closed without merging**
