### PR TITLE
Custom popups for cards that uses custom actions.

### PR DESCRIPTION
**Pull request by matrixx567**
Hy,

I really like the new custom actions feature but currently I miss the possibility using custom popup cards in an easy way.
This pull request implements the possibility to use custom popups with cards that already implements the custom actions feature. 

A popup for a card can be simply configured using variables. See the example below:

```yaml
    - type: 'custom:button-card'
      template: card_power_outlet
      entity: switch.power_outlet_livingroom
      variables:
        ulm_card_power_outlet_consumption_sensor: sensor.power_outlet_livingroom_consumption
        ulm_card_power_outlet_name: Power Outlet Livingroom
        ulm_custom_popup:
            template: "popup_power_outlet_stats"
            popup_variables:
              ulm_popup_power_outlet_sensor1: sensor.power_outlet_livingroom
              ulm_popup_power_outlet_sensor2: sensor.power_outlet_livingroom_consumption
              ulm_popup_power_outlet_graph_sensor: sensor.power_outlet_livingroom
              ulm_popup_power_outlet_entity: switch.power_outlet_livingroom        
```

For using a custom popup the variable `ulm_custom_popup` must be defined. This variable is a dictionary containing the name of the popup's custom button template (`template`). It is also possible to inject the necessary variables for the popup using `popup_variables`.

What do you think about this feature? 

(I'm not the JavaScript expert, so I would be open for suggestions and improvements.)

### CODE REVIEW

**Comment by matrixx567** [comment]
Hi @schumijo

I will answer you on this pull request for better traceability.
 
> Sorry I missed your PR. Sounds interesting to make more cards compatible with popups 👏 It will be a breaking change for users. Maybe we need to see if backward compatibility is possible.
> 
> Tell me if I am wrong but it is still necessarry to change action_xxx.yaml to update return entity ?
> 
> I will try to integrate your PR in my HA in next days 😉

The current implementation will make minor changes to the original functionality of the code. Therefore it adds some complexity to the actions_xx.yaml. The current implementation is fully backwards compatible with the lights popup.

What do you exactly mean by updating the return entity? If you mean the variables section the code will either provide the popup_variables if it is a custom_popup or the original three variables `ulm_popup_light_entity` etc. This is necessary for backwards compability with the lights, thermostat and media_player popups.

_If you plan to integrate this PR into the release, I would suggest to make some major changes to this PR:_

Therefore I would remove the sections for the light, media_player and thermostat in the actions_xx.yaml. This will result in much simpler code for the actions_xx.yaml files.  In the `card_lights.yaml` and the other ones the popup will be configured with the `ulm_custom_popup` variables in the custom fields. On the top level variables of the card I would suggest to keep the `ulm_card_light_enable_popup` variable. For the end user the configuration of the available cards (e.g., lights) will be the same.

I suggest to test this PR first.  
In my opinion it will provide the great possibility to simply integrate custom developed popups with already existing cards using the actions. In my case I`m currently developing a custom charts popup that I'm calling from a generic card.  This wouldn't be currently possible by using custom actions.

If you like the functionality I would do some refactoring described above including changes of the card_lights and others to simplify the integration.

Martin

**Comment by matrixx567** [comment]
> If you like the functionality I would do some refactoring described above including changes of the card_lights and others to simplify the integration.

I've already refactored the code and also include the overrides of the custom_actions within the icon_more_info_new. This also solves #893.

**Comment by matrixx567** [comment]
Add haptic configuration supported by the button card.

Possible options are `none, success, warning, failure, light, medium, heavy, selection`. Like the actions also the haptic can be overwritten for each card individually.

```yaml
ulm_custom_actions:
  variables:
    ulm_card_tap_action: "toggle"
    ulm_card_hold_action: "adaptive"
    ulm_card_double_tap_action: "more-info"
    ulm_icon_tap_action: "adaptive"
    ulm_icon_hold_action: "adaptive"
    ulm_icon_double_tap_action: "more-info"
    ulm_name_tap_action: "toggle"
    ulm_name_hold_action: "adaptive"
    ulm_name_double_tap_action: "more-info"

    ulm_card_tap_haptic: 'heavy'
    ulm_card_hold_haptic: 'medium'
    ulm_card_double_tap_haptic: 'medium'
    ulm_icon_tap_haptic: 'heavy'
    ulm_icon_hold_haptic: 'medium'
    ulm_icon_double_tap_haptic: 'medium'
    ulm_name_tap_haptic: 'heavy'
    ulm_name_hold_haptic: 'medium'
    ulm_name_double_tap_haptic: 'medium'
```

If this pull request will be accepted I will write the corresponding sections in the docs.
- how to use the custom popups
- how to configure the haptic control

**Comment by schumijo** [comment]
Hi @matrixx567 
Sure it will be accepted. Good job 👏👏
Sorry I didn't have time to make any test yesterday and I can't do it before next week. 
I will put my PRs as draft until I integrate your modifications

**Comment by basbruss** [comment]
Hi @matrixx567 

Your work together with @schumijo implementations are fantastic! 

Could you rebase this PR to the `release` branch as this PR is related to the backend framework?
See the contributing guidelines for more details

**Comment by matrixx567** [comment]
Hi @basbruss 

I've already done the rebase some minutes ago.
For now I think this PR is feature completed. I will start the documentation of the changes in an own PR.

It's time to test it, especially for the adaptive dashboard. I currently have no working adaptive dashboard to test it.
For the end user I think there shouldn't be any breaking changes.

For custom card developers there **could** be some breaking changes:
- The template `ulm_actions_card` can be removed
- The variable redirections for the `ulm_*_action` can be removed

**Implemented features:**
- Streamlining the redirection of custom_action variables. So the cards need not implement these redirections of the action variables
- Streamlining of necessary templates to use the custom actions. So it is only necessary to add the template `icon_more_info_new` or the new `extended_card` for the 2-Line cards (e.g., graph card)
- Implementation of haptic button support
- Adding the functionality to use custom popups with the custom_actions as described in my first comment. This adds the ability to add custom created popups in an easy way.

**Comment by basbruss** [comment]
> It seems that something got incredible wrong with my rebase (or is it correct?). Why will it say that there are 58 files changed instead of 19 I have actually changed?

There is nothing wrong. All the other files changed are commits that are already merged in the `main` branch but not in the release branch.
The best way to avoid it is to force push your commits to the `release` branch.
See for more information: https://docs.gitlab.com/ee/topics/git/git_rebase.html

**Review by basbruss — APPROVED** [review]

**Comment by matrixx567** [comment]
Hi @basbruss ,

I've chosen the wrong branch. Now it is clear what has happened.

Thank you.

**Comment by schumijo** [comment]
@matrixx567 
I did some test (except adaptive dashboard) and I confirm everything seems to be running fine.
Backward compatibility is also working
Amazing job !!!

**Pull request merged**
