### PR TITLE
Release V1.1.0

### PR DESCRIPTION
**Pull request by basbruss**

### CODE REVIEW

**Comment by mpeterson** [comment]
Please try to merge #915 before this one, as to make sure the custom card won't break due to the new pop up framework.

**Comment by basbruss** [comment]
@schumijo @stokkie90 @matrixx567 
Can you guys confirm by testing if everything works like it's intended?

**Comment by matrixx567** [comment]
@basbruss 

My dashboard is working without problems on the Release branch for two days now.

**Comment by schumijo** [comment]
Hi @basbruss 
Did some tests. Everything seems ok except radar button on weather popup.
Please merge #923 before release to fix

**Comment by basbruss** [comment]
> Hi @basbruss
> Did some tests. Everything seems ok except radar button on weather popup.
> Please merge #923 before release to fix

@schumijo 
Thanks for the check. The fix is merged so we are good to go!

**Review by schumijo — APPROVED** [review]

**Pull request merged**
