### PR TITLE
Create SE.yaml

### PR DESCRIPTION
**Pull request by EmilZackrisson**

### CODE REVIEW

**Comment by saxel** [comment]
Why not translate everything to Swedish?

**Comment by KaherdinTristan** [comment]
> Why not translate everything to Swedish?

I'm game. Bra förslag.

**Comment by CM000n** [comment]
In my opinion, it doesn't make much sense to merge this as long as no real translation is included.

**Comment by CM000n** [comment]
Hello @EmilZackrisson , could you still post a proper Swedish translation? 
Otherwise I would close the PR soon.

**Comment by KaherdinTristan** [comment]
`ulm_language_variables:
  variables:
    ulm_on: "av"
    ulm_off: "på"
    ulm_open: "öppen"
    ulm_closed: "stängd"
    ulm_unavailable: "ej tillänglig"
    ulm_standby: "standbyläge"
    ulm_idle: "idle"
    ulm_currency: "kr"`

**Comment by CM000n** [comment]
Thanks a lot! If you want, you can create a fork of this repo, and add the new file there with the appropriate translations, and then create your own pull request.
If you don't know how to do that and you don't want to deal with it, I can add the translation myself though 😉

**Comment by KaherdinTristan** [comment]
> Thanks a lot! If you want, you can create a fork of this repo, and add the new file there with the appropriate translations, and then create your own pull request. If you don't know how to do that and you don't want to deal with it, I can add the translation myself though 😉

Ok, so I have created that file in my fork. 
Could you do me the honor of walking me through the next steps to create a pull request? 
Is that created for a specific file or for the entire repo? 
😨

**Pull request closed without merging**
