### PR TITLE
Fix inconsistent naming with_

### PR DESCRIPTION
**Pull request by sildehoop**
With the card_cover_with_buttons is **with** used and card_light_slider not

Template name: card_battery
Template name: card_binary_sensor
Template name: card_binary_sensor_alert
Template name: card_cover_with_buttons **--> card_cover_buttons**
Template name: card_generic
Template name: card_generic_swap
Template name: card_graph
Template name: card_input_boolean
Template name: card_light
Template name: card_light_slider
Template name: card_light_slider_collapse
Template name: card_light_slider_horizontal
Template name: card_media_player
Template name: card_media_player_with_control **--> card_media_player_art**
Template name: card_media_player_with_controls **--> card_media_player_controls**
Template name: card_navigate
Template name: card_person
Template name: card_power_outlet
Template name: card_script
Template name: card_title
Template name: chip_back
Template name: chip_icon_double_state
Template name: chip_icon_only
Template name: chip_icon_state
Template name: chip_power_consumption
Template name: chip_presence_detection
Template name: chip_temperature

### CODE REVIEW

**Comment by CM000n** [comment]
Basically, I am with you. Inconsistent naings should be avoided. For some, this will certainly mean a breaking change.
@schumijo, @saxel, @bavo, what did you think?
Have you also checked whether the templates you changed also affect some of the custom cards in the repo @sildehoop ?
Btw. Can you possibly use DEV as a base branch? There have been some changes in the meantime that would currently prevent a merge.

**Comment by schumijo** [comment]
I am also with you. I think you should add a reference to old template name in legacy part of the yaml (look at the end of the file). This will prevent breaking some UI configurations. @Paddy0174  used this method when rewriting tben work.

**Comment by sildehoop** [comment]
As far is I now it doesn't affect any of the custom cards

And maybe we can put the old names in the legacy templates??

**Comment by sildehoop** [comment]
> I am also with you. I think you should add a reference to old template name in legacy part of the yaml (look at the end of the file). This will prevent breaking some UI configurations. @Paddy0174 used this method when rewriting tben work.

Sorry didn't see your comment will add them there!!

**Comment by bavo** [comment]
>  I think you should add a reference to old template name in legacy part of the yaml

We could also do something like this for the language variables where we change the template from:
```
name: "[[[ return variables.ulm_card_cover_buttons_name ]]]"
```
to something like this: 
```
# Deprecated! variables.ulm_card_cover_with_buttons_name will be removed in the next release
name: >
  [[[
    if ( variables.ulm_card_cover_buttons_name !== undefined && variables.ulm_card_cover_buttons_name !== '') {
      return variables.ulm_card_cover_buttons_name;
    }
    return  return variables.ulm_card_cover_with_buttons_name;
  ]]]
```

Where we support both configurations for 1 or 2 iterations. 
Or we could even do something like:
```
# Deprecated! variables.ulm_card_cover_with_buttons_name will be removed in the next release
name: >
  [[[
    if ( variables.ulm_card_cover_buttons_name !== undefined && variables.ulm_card_cover_buttons_name !== '') {
      return variables.ulm_card_cover_buttons_name;
    }
    return  return '⚠️' + variables.ulm_card_cover_with_buttons_name;
  ]]]
```
And append a warning sign to the deprecated resources. 

What do you guys think?

**Comment by schumijo** [comment]
HI @bavo,

Both propositions are good.
Mine for new template names support.
Yours for new variable names support.

**Comment by CM000n** [comment]
I think the approach with the legacy templates is a bit easier to mange, isn't it? Since we then only have one place in the code that we have to pay attention to.
With the approach of @bavo we would have several places that we would have to pay attention to and which are possibly even more difficult to maintain.

**Comment by sildehoop** [comment]
This old legacy template is not working for me, anyone nows how to fix and implement withe new naming?

```yaml
media_buttons:
  template: card_media_player_with_controls
  variables:
    ulm_card_media_player_with_controls_entity: "[[[ return variables.entity ]]]"
    ulm_card_media_player_with_controls_name: "[[[ return variables.name ]]]"
```
```yaml
 - type: "custom:button-card"
    template: media_buttons
    variables:
      entity: media_player.living_room_speaker_1
      name: "test"
```

**Comment by CM000n** [comment]
Will have to look into it

**Comment by CM000n** [comment]
What do you guys think, is this PR ready to merge, or should I rather give it a WIP label?

**Comment by sildehoop** [comment]
No not yet the legacy template in not working

**Comment by sildehoop** [comment]
But I don't now how to get it working

**Pull request closed without merging**
