### PR TITLE
Added new features to graph card (bar, dual graph, time)

### PR DESCRIPTION
**Pull request by mp-se**
This PR implements feature #137 and the options described in that thread. 

I can create a PR for the documentation in the other repo as well.

### CODE REVIEW

**Comment by CM000n** [comment]
Thank you very much! Should this PR also include the deletion of the `custom_card_mpse_dual_graph`? After all, this will make it obsolete.
The only additional benefit your custom card provides is showing both entity labels, if I see it correctly?

**Comment by CM000n** [comment]
I think it's enough if we just create an issue in the wiki repo first, that the doc of the card is to be revised. We have some catching up to do there anyway and currently no one can merge your PR there.
I hope that we can also merge the initial HACS support at the beginning of next week. After that, the wiki will have to be fundamentally adapted again anyway. 
So: Don't invest too much time in it, unless you have fun with it ;-)

**Comment by mp-se** [comment]
The PR for updating the documentation is now sumitted.

**Comment by CM000n** [comment]
Hello @mp-se. Wouldn't a separate branch possibly have been better? You push your changes to the vertical buttons now together with the changes to the graph card.

**Comment by mp-se** [comment]
Sure I can do that, will you create a new branch for me to push these changes to ? I can also push the weather card i created.

**Comment by CM000n** [comment]
> Sure I can do that, will you create a new branch for me to push these changes to ? I can also push the weather card i created.

I actually meant a separate branch on your side ;-) Here all changes from the different branches then run together again in dev.
But with seperate branches on your side you can develop the individual features and changes more targeted and we have it easier with the pull requests, if each PR only treats a single feature, or your changes of a single branch.

**Comment by mp-se** [comment]
Then i missunderstood you... Didnt recognize the github automatically included new commits on the same branch in the already submitted PR. my misstake.. will use branches for the different features instead.

**Pull request closed without merging**
