### PR TITLE
New Thermostat Card

### PR DESCRIPTION
**Pull request by mlittle408**
Here's a new thermostat card based on @TPX01 air-condition. This new card supports heat, cool and heat_cool hvac_modes.

### CODE REVIEW

**Comment by CM000n** [comment]
Nice! Thank you very much @mlittle408. I'm just wondering if it wouldn't be better to customize the existing card instead of adding a new custom card? Not that we don't end up with several thermostat cards that look the same and do the same thing, but just a little differently.

**Comment by mlittle408** [comment]
Sure that's up to you. No problem.

**Comment by CM000n** [comment]
lol, what was that? 😀 I actually thought we could discuss this here and work on it together.

**Comment by mlittle408** [comment]
Oh, I apologize. I'm pretty flexible. I'll do it however you like.

**Pull request closed without merging**
