### PR TITLE
Minimalist iOS theme with tapbar

### PR DESCRIPTION
**Pull request by LRvdLinden**
tapbar theme for iOS devices

### CODE REVIEW

**Comment by CM000n** [comment]
Hi @LRvdLinden, thank you very much for your contribution.
Can you please have a look at the code quality check.
1. .yaml files shouldn't start with a comment
2. your `minimalist-ios-tapbar.yaml` is missing a newline at the end of the file

**Comment by LRvdLinden** [comment]
@CM000n see PR https://github.com/UI-Lovelace-Minimalist/UI/pull/485

**Comment by CM000n** [comment]
Thank you for the changes @LRvdLinden. Btw. you don't have to open a new merge request if you make changes in the same branch of the original MR ;-)

Could you please describe a bit what exactly the changes are compared to the Tabbar Theme by @Ned-Tom and why they are necessary for iOS?

**Comment by LRvdLinden** [comment]
The current tap bar only shows half of the menu on iOS devices. This requires a separate theme for iOS.

**Review by basbruss — APPROVED** [review]
Tested on IOS devices 👍

**Comment by LRvdLinden** [comment]
Dankje @basbruss ik was er nog niet aan toegekomen

**Comment by antonio1475** [comment]
Hi @LRvdLinden. Thank you for your work on fixing the tapbar for iOS.

However, I found some issues on iPhone 13, compared to the mobile or mobile-tapbar:
1. iOS header (the sides of the notch) is white, "breaking" the background --> due to using mobile-tapbar as base. mobile is fine
2. non-Minimalist cards became squared
3. the tapbar touches iOS navigation bar, while having a lot of margin-top
4. the tapbar is white (this is pure opinion)
5. the tapbar sometimes (after refresh) was higher than expected, and it resized on tap, jumping a bit.

It looked like this:
image

I spent sime time tweaking it, and grabbing some of the mobile theme instead of mobile-tapbar, to fix it for me:
image

I don't know much much is due to different iPhones, so my modifications might definitely not work for all and there are many things I didn't grab from the mobile theme, but it works for me and I'd ask that it's considered for review of the theme. I don't know how to create PRs and work in Github, but anyone can use this of course and I'd be happy if someone uses to update the theme:

<details>
  <summary>minimalist-ios-tapbar-antonio</summary>
https://www.diffchecker.com/VDLU36f1
 
```
---
minimalist-ios-tapbar-antonio:
  # version 1.0.0
  # By LRvdLinden
  # Journal
  state-icon-color: "rgb(var(--color-theme))"
  border-radius: "20px"
  ha-card-border-radius: "var(--border-radius)"                                               
  error-color: "var(--google-red)"
  warning-color: "var(--google-yellow)"
  success-color: "var(--google-green)"
  info-color: "var(--google-blue)"
  divider-color: "rgba(var(--color-theme),.12)"
  accent-color: "var(--google-yellow)"
  card-mod-theme: "minimalist-ios-tapbar-antonio"
  card-mod-root: |
    app-toolbar {
      display: none;
    }
  header-height: "78px"
                            
                                               

  card-mod-view-yaml: |
    "*:first-child$": |
      #columns .column > * {
        padding-left: 5px;
        padding-right: 5px;
        padding-bottom: 5px;
      }

  # Move navbar
  card-mod-root-yaml: |
    ha-tabs$: |
      #tabsContent {
        width: 97%;
      }
    .: |
      @media (orientation: portrait) {
        a.menu-link[target="_blank"], ha-button-menu, ha-menu-button, [main-title] {
          display: none !important;
        }
        app-toolbar {
          padding-right: 0px;
          padding-left: 0px;
        }
      }
      ha-app-layout{
        transform: initial;
        padding: 0 !important;
        margin: 0 !important;
        width: 100%;
        height: 100% !important;
      }
      app-header {
        top: auto;
        bottom: 0;
        box-shadow: var(--footer-shadow);
        position: fixed;
        height: var(--header-height) !important;
      }
      app-toolbar {
        height: var(--header-height) !important;
        padding: 10px 0px !important;
      }
      #view {
        margin-top: calc(-1 * var(--header-height)) !important;
        padding-bottom: var(--header-height) !important;
      }
      ha-tabs {
        --paper-tabs-selection-bar-color: var(--header-tab-indicator-color) !important;
        --mdc-icon-size: 26px;
        display: flex;
        justify-content: space-between;
        padding: 10px;
        margin-top:15px;
        height:var(--header-height) !important;
      }
      paper-tab[aria-selected=true] {
        color: var(--header-active-tab-color);
        background-color: var(--header-active-tab-bg-color);
      }
      paper-tab {
        color: var(--header-all-tabs-color);
        border-radius: 25px;
        height:50px;
        padding: 0 20px;
      }

  # Color themes
  modes:
    light:
      # main interface colors
      primary-color: "#434343"
      google-red: "#F54436"
      google-green: "#01C852"
      google-yellow: "#FF9101"
      google-blue: "#3D5AFE"
      google-violet: "#661FFF"
      google-grey: "#BBBBBB"
      color-red: "245, 68, 54"
      color-green: "1, 200, 82"
      color-yellow: "255, 145, 1"
      color-blue: "61, 90, 254"
      color-purple: "102, 31, 255"
      color-grey: "187, 187, 187"
      color-pink: "233, 30, 99"
      color-theme: "51,51,51"
      color-background-yellow: "250, 250, 250"
      color-background-blue: "250, 250, 250"
      color-background-green: "250, 250, 250"
      color-background-red: "250, 250, 250"
      color-background-pink: "250, 250, 250"
      color-background-purple: "250, 250, 250"
      color-yellow-text: "var(--primary-text-color)"
      color-blue-text: "var(--primary-text-color)"
      color-green-text: "var(--primary-text-color)"
      color-red-text: "var(--primary-text-color)"
      color-pink-text: "var(--primary-text-color)"
      color-purple-text: "var(--primary-text-color)"
      opacity-bg: "1"
      # Header / Footer
      header-active-tab-color: "rgb(var(--color-blue))"
      header-active-tab-bg-color: "rgba(var(--color-blue), .3)"
      header-all-tabs-color: "var(--paper-item-icon-color)"
      header-tab-indicator-color: "rgba(0, 0, 0, 0)"
      app-header-text-color: "var(--primary-text-color)"
      app-header-background-color: "var(--primary-background-color)"
      paper-tabs-selection-bar-color: "var(--primary-text-color)"
      footer-shadow: "0px -1px 3px 0px rgba(0,0,0,0.12)"
      # background and sidebar
      card-background-color: "#FAFAFA"
      primary-background-color: "#EFEFEF"
      secondary-background-color: "#EFEFEF"
      # text
      primary-text-color: "#212121"
      # slider
      slider-color: "rgb(var(--google-blue))"
      slider-bar-color: "rgba(var(--google-blue),0.38)"
      # cards
      box-shadow: "0px 2px 4px 0px rgba(0,0,0,0.16)"
      ha-card-box-shadow: "var(--box-shadow)"
      # sidebar
      sidebar-selected-text-color: "rgb(var(--color-blue))"
      sidebar-selected-icon-color: "rgb(var(--color-blue))"
      sidebar-text-color: "#80868b"
      # switch
      switch-checked-color: "rgb(var(--color-blue))"
      # media player
      mini-media-player-accent-color: "rgb(var(--color-blue))"
    dark:
      # main interface colors
      primary-color: "#89B3F8"
      google-red: "#F18B82"
      google-green: "#80C994"
      google-yellow: "#FCD663"
      google-blue: "#89B3F8"
      google-violet: "#BB86FC"
      google-grey: "#BBBBBB"
      color-red: "241, 139, 130"
      color-green: "128, 201, 148"
      color-yellow: "252, 214, 99"
      color-blue: "137, 179, 248"
      color-theme: "221,221,221"
      color-purple: "102, 31, 255"
      color-grey: "187, 187, 187"
      color-pink: "233, 30, 99"
      color-amber: "255, 145, 1"
      color-background-yellow: "var(--color-yellow)"
      color-background-blue: "var(--color-blue)"
      color-background-green: "var(--color-green)"
      color-background-red: "var(--color-red)"
      color-background-pink: "var(--color-pink)"
      color-background-purple: "var(--color-purple)"
      color-yellow-text: "var(--color-yellow)"
      color-blue-text: "var(--color-blue)"
      color-green-text: "var(--color-green)"
      color-red-text: "var(--color-red)"
      color-pink-text: "var(--color-pink)"
      color-purple-text: "var(--color-purple)"
      opacity-bg: "0.1"
      # Header / Footer
      header-active-tab-color: "rgb(var(--color-amber))"
      header-active-tab-bg-color: "rgba(var(--color-amber), .3)"
      header-all-tabs-color: "var(--paper-item-icon-color)"
      header-tab-indicator-color: "rgba(0, 0, 0, 0)"
      app-header-text-color: "var(--primary-text-color)"
      app-header-background-color: "var( --ha-card-background, var(--card-background-color, rgb(29, 29, 29)) )"
      paper-tabs-selection-bar-color: "var(--primary-text-color)"
      footer-shadow: "0px -1px 3px 0px rgba(0,0,0,0.12)"
      # background and sidebar
      card-background-color: "#1D1D1D"
      primary-background-color: "#121212"
      secondary-background-color: "#121212"
      # text
      primary-text-color: "#DDDDDD"
      # floating button text color
      mdc-theme-on-secondary: "var(--card-background-color)"
      # Sidebar
      sidebar-selected-text-color: "rgb(var(--color-amber))"
      sidebar-selected-icon-color: "rgb(var(--color-amber))"
      # Slider
      slider-color: "rgb(var(--color-blue))"
      slider-bar-color: "rgba(var(--color-blue),0.38)"
      # card
      box-shadow: "none"
      # media player
      mini-media-player-accent-color: "var(--google-blue)"
      # Journal
      state-icon-color: "rgb(var(--color-theme))"
```
  
</details>

**Comment by LRvdLinden** [comment]
Hi @antonio1475, thanks for the input. I will check it on more devices and will make a PR with an update.

**Comment by antonio1475** [comment]
@LRvdLinden first, thank you.

Although I personally don't like a white tapbar in light mode (gray blends in much more, and it has a border-top to separate), in dark-mode there was no separation (a border-top could probably be added). In any case, I guess I see your point of the tapbar being a different color. So, based on your 1.0.1 from PR #582 , I edited 3 lines to fix that **in iOS, because on desktop it doesn't fix it** (the tapbar stays the same color as the background), **I don't know why**:

<details>
  <summary>minimalist-ios-tapbar-antonio 1.0.1 - fix header/notch sides color in iOS</summary>
https://www.textcompare.org/yaml/?id=624e130377ebb38f98169418
 
```
---
minimalist-ios-tapbar-antonio:
  # version 1.0.1
  # By LRvdLinden
  # Journal
  state-icon-color: "rgb(var(--color-theme))"
  border-radius: "20px"
  ha-card-border-radius: "var(--border-radius)"                                               
  error-color: "var(--google-red)"
  warning-color: "var(--google-yellow)"
  success-color: "var(--google-green)"
  info-color: "var(--google-blue)"
  divider-color: "rgba(var(--color-theme),.12)"
  accent-color: "var(--google-yellow)"
  card-mod-theme: "minimalist-ios-tapbar-antonio"
  card-mod-root: |
    app-toolbar {
      display: none;
    }
  header-height: "78px"
                            
                                               

  card-mod-view-yaml: |
    "*:first-child$": |
      #columns .column > * {
        padding-left: 5px;
        padding-right: 5px;
        padding-bottom: 5px;
      }

  # Move navbar
  card-mod-root-yaml: |
    ha-tabs$: |
      #tabsContent {
        width: 97%;
      }
    .: |
      @media (orientation: portrait) {
        a.menu-link[target="_blank"], ha-button-menu, ha-menu-button, [main-title] {
          display: none !important;
        }
        app-toolbar {
          padding-right: 0px;
          padding-left: 0px;
        }
      }
      ha-app-layout{
        transform: initial;
        padding: 0 !important;
        margin: 0 !important;
        width: 100%;
        height: 100% !important;
      }
      app-header {
        top: auto;
        bottom: 0;
        box-shadow: var(--footer-shadow);
        position: fixed;
        height: var(--header-height) !important;
      }
      app-toolbar {
        height: var(--header-height) !important;
        padding: 10px 0px !important;
        background: var( --ha-card-background, var(--card-background-color) );
      }
      #view {
        margin-top: calc(-1 * var(--header-height)) !important;
        padding-bottom: var(--header-height) !important;
      }
      ha-tabs {
        --paper-tabs-selection-bar-color: var(--header-tab-indicator-color) !important;
        --mdc-icon-size: 26px;
        display: flex;
        justify-content: space-between;
        padding: 10px;
        margin-top:15px;
        height:var(--header-height) !important;
      }
      paper-tab[aria-selected=true] {
        color: var(--header-active-tab-color);
        background-color: var(--header-active-tab-bg-color);
      }
      paper-tab {
        color: var(--header-all-tabs-color);
        border-radius: 25px;
        height:50px;
        padding: 0 20px;
      }

  # Color themes
  modes:
    light:
      # main interface colors
      primary-color: "#434343"
      google-red: "#F54436"
      google-green: "#01C852"
      google-yellow: "#FF9101"
      google-blue: "#3D5AFE"
      google-violet: "#661FFF"
      google-grey: "#BBBBBB"
      color-red: "245, 68, 54"
      color-green: "1, 200, 82"
      color-yellow: "255, 145, 1"
      color-blue: "61, 90, 254"
      color-purple: "102, 31, 255"
      color-grey: "187, 187, 187"
      color-pink: "233, 30, 99"
      color-theme: "51,51,51"
      color-background-yellow: "250, 250, 250"
      color-background-blue: "250, 250, 250"
      color-background-green: "250, 250, 250"
      color-background-red: "250, 250, 250"
      color-background-pink: "250, 250, 250"
      color-background-purple: "250, 250, 250"
      color-yellow-text: "var(--primary-text-color)"
      color-blue-text: "var(--primary-text-color)"
      color-green-text: "var(--primary-text-color)"
      color-red-text: "var(--primary-text-color)"
      color-pink-text: "var(--primary-text-color)"
      color-purple-text: "var(--primary-text-color)"
      opacity-bg: "1"
      # Header / Footer
      header-active-tab-color: "rgb(var(--color-blue))"
      header-active-tab-bg-color: "rgba(var(--color-blue), .3)"
      header-all-tabs-color: "var(--paper-item-icon-color)"
      header-tab-indicator-color: "rgba(0, 0, 0, 0)"
      app-header-text-color: "var(--primary-text-color)"
      app-header-background-color: "var(--primary-background-color)"
      paper-tabs-selection-bar-color: "var(--primary-text-color)"
      footer-shadow: "0px -1px 3px 0px rgba(0,0,0,0.12)"
      # background and sidebar
      card-background-color: "#FAFAFA"
      primary-background-color: "#EFEFEF"
      secondary-background-color: "#EFEFEF"
      # text
      primary-text-color: "#212121"
      # slider
      slider-color: "rgb(var(--google-blue))"
      slider-bar-color: "rgba(var(--google-blue),0.38)"
      # cards
      box-shadow: "0px 2px 4px 0px rgba(0,0,0,0.16)"
      ha-card-box-shadow: "var(--box-shadow)"
      # sidebar
      sidebar-selected-text-color: "rgb(var(--color-blue))"
      sidebar-selected-icon-color: "rgb(var(--color-blue))"
      sidebar-text-color: "#80868b"
      # switch
      switch-checked-color: "rgb(var(--color-blue))"
      # media player
      mini-media-player-accent-color: "rgb(var(--color-blue))"
    dark:
      # main interface colors
      primary-color: "#89B3F8"
      google-red: "#F18B82"
      google-green: "#80C994"
      google-yellow: "#FCD663"
      google-blue: "#89B3F8"
      google-violet: "#BB86FC"
      google-grey: "#BBBBBB"
      color-red: "241, 139, 130"
      color-green: "128, 201, 148"
      color-yellow: "252, 214, 99"
      color-blue: "137, 179, 248"
      color-theme: "221,221,221"
      color-purple: "102, 31, 255"
      color-grey: "187, 187, 187"
      color-pink: "233, 30, 99"
      color-amber: "255, 145, 1"
      color-background-yellow: "var(--color-yellow)"
      color-background-blue: "var(--color-blue)"
      color-background-green: "var(--color-green)"
      color-background-red: "var(--color-red)"
      color-background-pink: "var(--color-pink)"
      color-background-purple: "var(--color-purple)"
      color-yellow-text: "var(--color-yellow)"
      color-blue-text: "var(--color-blue)"
      color-green-text: "var(--color-green)"
      color-red-text: "var(--color-red)"
      color-pink-text: "var(--color-pink)"
      color-purple-text: "var(--color-purple)"
      opacity-bg: "0.1"
      # Header / Footer
      header-active-tab-color: "rgb(var(--color-amber))"
      header-active-tab-bg-color: "rgba(var(--color-amber), .3)"
      header-all-tabs-color: "var(--paper-item-icon-color)"
      header-tab-indicator-color: "rgba(0, 0, 0, 0)"
      app-header-text-color: "var(--primary-text-color)"
      app-header-background-color: "var(--primary-background-color)"
      paper-tabs-selection-bar-color: "var(--primary-text-color)"
      footer-shadow: "0px -1px 3px 0px rgba(0,0,0,0.12)"
      # background and sidebar
      card-background-color: "#1D1D1D"
      primary-background-color: "#121212"
      secondary-background-color: "#121212"
      # text
      primary-text-color: "#DDDDDD"
      # floating button text color
      mdc-theme-on-secondary: "var(--card-background-color)"
      # Sidebar
      sidebar-selected-text-color: "rgb(var(--color-amber))"
      sidebar-selected-icon-color: "rgb(var(--color-amber))"
      # Slider
      slider-color: "rgb(var(--color-blue))"
      slider-bar-color: "rgba(var(--color-blue),0.38)"
      # card
      box-shadow: "none"
      # media player
      mini-media-player-accent-color: "var(--google-blue)"
      # Journal
      state-icon-color: "rgb(var(--color-theme))"
```
</details>

image

Just my 2 cents, there's probably a better way to do it :)

**Comment by LRvdLinden** [comment]
@antonio1475 I will update the PR! This will work!

**Comment by LRvdLinden** [comment]
@antonio1475 New PR done! https://github.com/UI-Lovelace-Minimalist/UI/pull/589

**Pull request merged**
