### PR TITLE
Fix log messages "Detected blocking call' and hanging issues #3

### PR DESCRIPTION
**Pull request by wilbiev**
## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [X] I have followed the [contribution guidelines](https://github.com/UI-Lovelace-Minimalist/UI/blob/main/.github/CONTRIBUTING.md)
    - [ ] This PR is for a custom-card or documentation change and therefore directed to the `main` branch.
    - [X] This PR is for a official card or any other directly to the integration related change and therefore directed to the `release` branch.

### CODE REVIEW

**Comment by wilbiev** [comment]
Check fails while isort is using deprecated options in the check. Updated .pre-commit-config.yaml included in PR.

**Comment by wilbiev** [comment]
@stokkie90 can you please review this PR? All checks have passed. It solves some major issues and will make a lot of UI Minimalist users happy. Thanks in advance.

**Review by stokkie90 — APPROVED** [review]
LGTM

**Comment by stokkie90** [comment]
@basbruss would you be able to create a new release once this is merged? I've been out of touch with this repo.

**Pull request merged**
