### PR TITLE
Rework thermostat card to new templates

### PR DESCRIPTION
**Pull request by schumijo**
Rework thermostat card to new templates

Issue #51 and #4

### CODE REVIEW

**Review by basbruss — CHANGES_REQUESTED** [review]
The `NL.yaml` file has some small translation errors.
The correct translations are:
```
ulm_heat: "verwarmen"
ulm_cool: "koelen"
```

**Comment by CM000n** [comment]
It looks like you still have some trailing whitespaces and missing line endings in your code @schumijo . If you want I can still merge though. Pre-commit should fix these flaws automatically.

**Comment by CM000n** [comment]
Btw.the german translation are also a little wrong

These should be like this

languages/DE.yaml
```
    ulm_heat: "wärmen"
    ulm_cool: "kühlen"
```

languages/DE_capitalized.yaml
```
    ulm_heat: "Wärmen"
    ulm_cool: "Kühlen"
```

**Comment by schumijo** [comment]
Google translate is not my friend :-)
Yes please merge
I will take a look to add pre-commit to VScode

**Comment by CM000n** [comment]
I can highly recommend deepl as translator:
https://www.deepl.com/translator
10x better than google IMHO

Should I also do the translation fixes for DE. Or will you do it yourself?

**Pull request merged**
