### PR TITLE
Saxel Fan Updates

### PR DESCRIPTION
**Pull request by benbur98**
I have worked on a few updates to @saxel fan card.
Have incorporated some of @sildehoop work with the percentage/humidity labels (these can be optioned out if not desired), from his PR #134 

I have added the option to remove the Oscillation button as requested in #107 . With changing the Service of this button it is more complicated, could someone with an air purifier comment on what service (and it's data) they would specifically like - I have started to add this option but currently only oscillation will work (as previous) as i haven't added anything to change the Service data.

Planning on implementing the Horizontal card layout also.

### CODE REVIEW

**Comment by benbur98** [comment]
Quick and dirty Horizontal Mode added.
As mentioned in #134 , I think the card needs rebasing off of the Light card as it is significantly different in what is fairly similar operation. Will look into this.

**Comment by shift-del1** [comment]
@benbur98: I have Xiaomi Mi Air Purifier 2S and 3, so I can do the tests. From my point of view the only reasonable servise to be assigned to the button would be the looping between presets, this is what the button/touch screen does too. One press, Auto, press again, Silent, press again Manual/Favorite and so on (or if there are levels, those ones). In my case the attributes are the following:
  preset_modes:
    - Auto
    - Silent
    - Favorite
    - Idle/Fan (2S/3)
  preset_mode: Favorite
so fan.set_preset_mode would seem to be the right choice (personally I don't modify the preset manually). Favorite and Fan modes have number entities, so long pressing the button could be used to alter somehow the number entity assigned to that specific mode (through number.set_value). These are just ideas, persionally I would remove the button completely 😊

**Comment by benbur98** [comment]
Thanks for the info. Implementing auto mode toggle should be doable. The trouble really is keeping it consistent between different fans - unfortunately there is no ‘get available presets’ option so without restricting it by variables it’s a very specific option.
Also I have added the option to remove the button now if you like.

**Comment by shift-del1** [comment]
@benbur98 I replaced the yaml with yours, but I got an error for label (I defined the variables for temp and hum attributes and the one to remove the button. After hardcoded a value for label, I got this:
TypeError: Cannot assign to read only property '0' of object '[object Array]'
Any suggestion where did I go wrong? Thank you.

**Comment by benbur98** [comment]
@shift-del1 Thanks for checking this out. How did you define the variables, can you share your YAML? Also what do you mean by 'hardcoded a value for label'.

**Comment by benbur98** [comment]
Note: This check is only spelling due to the spelling of 'Collapsable' in the Doc - I Have spelt it this way as changing the variable spelling to be correct 'Collapsible' is not worth the breaking change.

**Comment by shift-del1** [comment]
@benbur98: I reverted back my config to the original fan card, so I can not show my YAML (sorry). "Hardcoded" means I replaced the label section with a string (so skipped the whole function which defines the string to show as a label). Technically it should simplyfy the card while loosing its flexibility, but for my test it should have been enough (but it wasn't :-D). I'm sure it is hard to help without data, just wanted to ask if you faced the same previously.

**Pull request merged**
