### PR TITLE
Custom Card "Room" support for new popups

### PR DESCRIPTION
**Pull request by mpeterson**
Add support for the new popup framework while maintaining backwards compatibility with the old one.

### CODE REVIEW

**Comment by mpeterson** [comment]
@matrixx567 could you review that this is good according to your changes on #878  ?

**Comment by mpeterson** [comment]
@basbruss it would be awesome if you can merge this before releasing the next release, as not to break this custom card due to the new popups framework. Cheers!

**Comment by matrixx567** [comment]
Hi @mpeterson,

I did not test your card, but after a short code review it looks quite well. For calling the popups on light and climate your implementation is sufficient. 

I think you missed the the template `ulm_custom_actions` if you use the `ulm_actions_card` by itself. If you only use the custom popups functionality the `ulm_custom_action` template isn't necessary. 

Yesterday I've written a short documentation how to use the custom actions in PR #910. I think section "Individual implementation" will give some help.

Only a short notice to be streamlined with the internal cards:
You can also implement the `ulm_custom_actions` and `ulm_actions_card` on your card itself. Therefore the actions for the card could easily be overloaded.
The internal cards don't use the icon and name field of the card itself. They are implementing two custom fields, the icon (`item1`) and the name (`item2`) as separate custom button cards. Therefore it will be possible to use the `ulm_actions_icon` and `ulm_actions_name`.

**Comment by basbruss** [comment]
@mpeterson I have rebased the PR to `release` so it's launched at the same time as the enhanced popups framework.

**Comment by mpeterson** [comment]
> Hi @mpeterson,
> 
> I did not test your card, but after a short code review it looks quite well. For calling the popups on light and climate your implementation is sufficient.
> 
> I think you missed the the template `ulm_custom_actions` if you use the `ulm_actions_card` by itself. If you only use the custom popups functionality the `ulm_custom_action` template isn't necessary.
> 

for now I only brought the custom popups only, but I might add the custom actions in the future to make it more flexible.

> Yesterday I've written a short documentation how to use the custom actions in PR #910. I think section "Individual implementation" will give some help.
> 

amazing, I'll give it a read for the future, thanks :)


> Only a short notice to be streamlined with the internal cards: You can also implement the `ulm_custom_actions` and `ulm_actions_card` on your card itself. Therefore the actions for the card could easily be overloaded. The internal cards don't use the icon and name field of the card itself. They are implementing two custom fields, the icon (`item1`) and the name (`item2`) as separate custom button cards. Therefore it will be possible to use the `ulm_actions_icon` and `ulm_actions_name`.

yeah, it's a sensible improvement. I'll see when I'll be able to do it. Thanks!

**Comment by mpeterson** [comment]
> @mpeterson I have rebased the PR to `release` so it's launched at the same time as the enhanced popups framework.

sounds great, thanks!

**Review by basbruss — APPROVED** [review]

**Pull request merged**
