### PR TITLE
Fix card naming

### PR DESCRIPTION
**Pull request by sildehoop**
Remake of #86
I have recently seen more confusion around the card_media_player_controls and card_media_player_control naming. I think it is beter to adres this now instead of delaying it.

Template name: card_battery
Template name: card_binary_sensor
Template name: card_binary_sensor_alert
Template name: card_cover_with_buttons --> card_cover_buttons
Template name: card_generic
Template name: card_generic_swap
Template name: card_graph
Template name: card_input_boolean
Template name: card_light
Template name: card_light_slider
Template name: card_light_slider_collapse
Template name: card_light_slider_horizontal
Template name: card_media_player
Template name: card_media_player_with_control --> card_media_player_art
Template name: card_media_player_with_controls --> card_media_player_controls
Template name: card_navigate
Template name: card_person
Template name: card_power_outlet
Template name: card_script
Template name: card_title
Template name: chip_back
Template name: chip_icon_double_state
Template name: chip_icon_only
Template name: chip_icon_state
Template name: chip_power_consumption
Template name: chip_presence_detection
Template name: chip_temperature

### CODE REVIEW

**Comment by CM000n** [comment]
Seems you mixed up your changes on you inpu number card together with the renamings?
Makes the PR harder to read.

But yeah, I'm absolutely with you.
People are confused and we have to change it better sooner then later

**Comment by sildehoop** [comment]
Ohh sorry didn't notice

**Comment by sildehoop** [comment]
update #349 after push or vice versa

**Review by CM000n — APPROVED** [review]

**Comment by CM000n** [comment]
If I see it correctly, this will break previous uses of the cards, right?
Is there a way to maintain compatibility with the old naming convention or do we just want to make a hard cut and put some information about it in the release notes?

**Comment by sildehoop** [comment]
Yes your right and I don't now it it is the right decision to keep dragging the old templates and try to support them. if jou want to improve you need to have braking changes. I will try making a legacy templates with the old naming and add the renaming for #349

**Comment by CM000n** [comment]
@stokkie90 how do you feel about it?
In my opinion we should go for a hard cut here

**Comment by CM000n** [comment]
Think we can merge it @sildehoop 
E
We should just take care of a proper breaking change message in the release noted

**Review by CM000n — APPROVED** [review]

**Comment by sildehoop** [comment]
should I remove the legacy templates ??

**Comment by CM000n** [comment]
> should I remove the legacy templates ??

Any more opinions on that @schumijo, @bavo ..?

**Comment by schumijo** [comment]
> > should I remove the legacy templates ??
> 
> Any more opinions on that @schumijo, @bavo ..?

Maybe we could keep the legacy template for now and then removed them in 2 or 3 release as done by HA with deprecated integration.
It's just an idea...

**Comment by bavo** [comment]
Yeah maybe keep them, but deprecate them in the release notes

**Comment by CM000n** [comment]
I've merged it now and noted it in the Release Note Draf here: https://github.com/UI-Lovelace-Minimalist/UI/pull/337
Please add/correct if needed.

**Pull request merged**
