### PR TITLE
Custom card device tracker

### PR DESCRIPTION
**Pull request by aehru**

### CODE REVIEW

**Review by basbruss — CHANGES_REQUESTED** [review]
Could you change the title to be inline with the title format from #440 ?

**Comment by aehru** [comment]
> Could you change the title in the readme.md to be inline with the title format from #440 ?

Oh yes, didn't saw that, will do it.

**Review by basbruss — APPROVED** [review]

**Comment by basbruss** [comment]
What are the appropriate translations? as some are direct translations of `online` and `offline`, and some `home` and `not_home`

**Comment by aehru** [comment]
This require more translations for all languages. Or I can apply same translations as 'home' and 'not_home' as I started to do but was not sure what is best option.

**Comment by CM000n** [comment]
The best would be to use "Online" and "Offline" as placeholders if you don't know the correct translation.
In German it would be wrong to translate a device as "Zu Hause" if I want to express its power-on or connection status. Unless you are talking about mobile devices and want to describe geographically whether they are at home or not ;-)

**Comment by aehru** [comment]
The purpose is to use it for mobile or non mobile devices so I will update all with placeholders as suggested.

**Comment by basbruss** [comment]
> The best would be to use "Online" and "Offline" as placeholders if you don't know the correct translation. In German it would be wrong to translate a device as "Zu Hause" if I want to express its power-on or connection status. Unless you are talking about mobile devices and want to describe geographically whether they are at home or not ;-)

I agree with this. But when you want to describe their geographically state. It's better to use the already existing `ulm_person_state_*` translations, to avoid over-cluttering of the translations files.

**Review by basbruss — APPROVED** [review]

**Review by basbruss — APPROVED** [review]

**Pull request merged**
