### PR TITLE
Creation of popup thermostat which uses preset_mode instead of state.

### PR DESCRIPTION
**Pull request by MatthewSean**
I created this for my own use, and thought I should share.  Hopefully, I have done this in the correct way.  If not let me know.

### CODE REVIEW

**Comment by basbruss** [comment]
@schumijo What do you think of this addition? Can we combine it with the original one?

**Comment by basbruss** [comment]
> @basbruss
> 
> Yes seems to be possible to combine with original one by adding a variable to choose between hvac mode and preset mode.

Okay I will try to add this feature to the original one with some commits to this PR. @MatthewSean are you okay with that?

**Comment by MatthewSean** [comment]
Please feel free to add, sorry for the late reply.

**Comment by basbruss** [comment]
@MatthewSean I think I am done with combining both features. Could you test if you are satisfied with the result?

To switch to preset mode just add to your card config
```yaml
variables:
  ulm_card_thermostat_enable_popup: true
  ulm_card_thermostat_preset_mode: true
```

**Comment by MatthewSean** [comment]
Please go ahead.

**Review by basbruss — APPROVED** [review]

**Pull request merged**
