### PR TITLE
Add Adaptive Dashboard

### PR DESCRIPTION
**Pull request by basbruss**
Give support for advanced tablet (split) view  as can be found on Behance:
Uses `double_tap_action` and a `input_select` as helper.
Requirements:

- state-switch: https://github.com/thomasloven/lovelace-state-switch
- layout-card:  https://github.com/thomasloven/lovelace-layout-card

minimalist_adaptive_dash

image

Still to do:

- [x] optimize popups --> done with #679  
- [x] add new documentation page to wiki
- [ ] alter documentation for individual cards
- [x] Adapt backend framework for the new dashboard --> done with https://github.com/basbruss/UI/pull/2 
- [x] add support and popup-themed files for other device-types
- [ ] Automatic setup possible with python helpers?

### CODE REVIEW

**Comment by jrspowers** [comment]
hey @basbruss when is this coming out this looks very nice on the picture?  seem very useful?

**Comment by basbruss** [comment]
Thanks @jrspowers!

I still need to write the documentation which will take some time.
There is also a bug with the latest release of the `state-switch-card`: https://github.com/thomasloven/lovelace-state-switch/issues/83
So we also need to wait until that's fixed. Or people need to revert to an older version of it.

**Comment by jrspowers** [comment]
@basbruss a okay no problem then I'll see it appear when it's in order thanks in advance for your answer

**Comment by basbruss** [comment]
Ready for release 🎉 
preview:
minimalist_adaptive_dash

**Comment by jrspowers** [comment]
very nice man looking forward to it when is this coming out ?

**Pull request merged**
