### PR TITLE
Add custom_card_drealine_roomview

### PR DESCRIPTION
**Pull request by Drealine**
First release of custom_card_drealine_roomview.

### CODE REVIEW

**Comment by basbruss** [comment]
Hi @Drealine 

Thanks for your sharing your card with the community.

Could you also provide a documentation file as the other cards have? This will help users massively with understanding and integrating your card.
Also please take a good look here: https://ui-lovelace-minimalist.github.io/UI/development/custom_cards/ the code needs to be in line with some guidelines before merging.

**Comment by Drealine** [comment]
HI @basbruss 

Thank you for your answer.

Check code quality is ok but juste one problem appear :  

`trim trailing whitespace` Can tell me what can I do ?

**Comment by basbruss** [comment]
Hi @Drealine 

I can run pre-commit on my system to remove all whitespace automatically. Doing it by hand can be very time-consuming.

**Comment by Drealine** [comment]
> Hi @Drealine
> 
> I can run pre-commit on my system to remove all whitespace automatically. Doing it by hand can be very time-consuming.

Sorry, I see your last message but I remove last whitespaces ahah.

I make the readme this week :)

**Comment by Drealine** [comment]
Hi @basbruss 
Can you review all commits and let me know if it's ok for code quality and readme ? :)

**Review by basbruss — APPROVED** [review]

**Pull request merged**
