### PR TITLE
Update ES.yaml

### PR DESCRIPTION
**Pull request by revin34**
ulm_heat: "Caliente" is an adjective and means "hot" in english. 
ulm_cool: "Enfriar"  is a verb and means "to cool" in english. In spanish, different words are used depending if it's a verb or an adjective.

I propose to change to "Calor" and "frio" as these are the usual names seen in climate devices

### CODE REVIEW

**Comment by denes44** [comment]
Hi,
I think you should use the dev branch, because every new feature is first done in the dev brach, and later moved to the main one.
The language file is newer in the dev branch, there are some new variables for the alarm chip, it would be good if you could translate them as well.

**Comment by revin34** [comment]
Hi @denes44 ,

Ok. no problem. Do I have to close this one a create another PR from dev branch

**Comment by sildehoop** [comment]
No just change the destination branch.

**Comment by CM000n** [comment]
Changed it from main to dev ;-)

**Comment by revin34** [comment]
sorry for messing up but I'm not a programmer :-(.

I've updated the codes for the alarm.

**Comment by CM000n** [comment]
really no problem. you did nothing wrong. thank you for your contribution :-)

**Pull request merged**
