### PR TITLE
Update Czech & Slovak translations.

### PR DESCRIPTION
**Pull request by mstefany**
Vacuum translations updated according to Home Assistant Core.

### CODE REVIEW

**Comment by mstefany** [comment]
I have rebased PR against release branch, so that it includes only translation update commit.

**Comment by CM000n** [comment]
Hi, thnak you!
Your PR duplicates https://github.com/UI-Lovelace-Minimalist/UI/pull/428/files in some areas and therefore has merge conflicts.
Can you please have another look?

**Comment by mstefany** [comment]
Well, it looks like you merged @kubiksamek 's ad-hoc translation first, which does not match strings from Home Assistant Core. I can update/rebase the PR to match Home Assistant Core strings or just close it.

**Comment by CM000n** [comment]
I would be happy and grateful if you could update your PR again. 
Thank you very much for your effort!

**Comment by CM000n** [comment]
Ah, I just see that you have already done that :-D

**Review by CM000n — APPROVED** [review]

**Pull request merged**
