### PR TITLE
Button Cards Templates split

### PR DESCRIPTION
**Pull request by sildehoop**
I have updated my pr #67
Beginning to move to new file structure https://github.com/UI-Lovelace-Minimalist/UI/discussions/105#discussioncomment-1866879

### CODE REVIEW

**Comment by CM000n** [comment]
Wow, great work @sildehoop ! I like it. But that's a big change. Could you maybe support here with the review, @schumijo, @basbruss, @bavo, etc...?

**Review by schumijo — APPROVED** [review]
I just apply your changes to my current dashboard and all works correctly.
I didn't test all cards

**Comment by bavo** [comment]
I'm in favor of this change. It makes it much more easy to find the correct template if your developing your own cards or if you want to make changes :+1:

**Comment by basbruss** [comment]
I'm also in favor of this change:) As it is much faster to debug and develop new templates. Instead of endless scrolling through more than 2000 lines of code.  I think we can also include a folder with translations files (also include the custom_cards translations) for as long translations are not  yet supported within the HACS repo.

**Comment by sildehoop** [comment]
> I'm in favor of this change. It makes it much more easy to find the correct template if your developing your own cards or if you want to make changes 👍
> 
> @CM000n The changes look good. It's just the button_card_templates split up into different files 😉

That is exactly what I did, copy paste copy paste copy paste copy paste......😂

**Pull request merged**
