### PR TITLE
Ability to customize actions

### PR DESCRIPTION
**Pull request by schumijo**
Hi,

I am working on the ability to customize tap_action, hold_action and double_action on all cards.
A new global_config.yaml ile is available to define actions.
Custom actions will be available on card, icon and name !

- [ ] Update internal templates UPDATE : still to-do person card and binary sensor alert card
- [x] Add popup action on available cards
- [x] Update docs

### CODE REVIEW

**Comment by basbruss** [comment]
@schumijo Nice idea!
Could you reassign the PR to the `release` branch?

**Comment by basbruss** [comment]
> @basbruss ; I accidentally pushed a commit to release branch :( Can you remove it ?

I am not able to. I think you can revert it yourself through git(-desktop) https://stackoverflow.com/questions/22682870/how-can-i-undo-pushed-commits-using-git

**Comment by schumijo** [comment]
> > @basbruss ; I accidentally pushed a commit to release branch :( Can you remove it ?
> 
> I am not able to. I think you can revert it yourself through git(-desktop) https://stackoverflow.com/questions/22682870/how-can-i-undo-pushed-commits-using-git

Done thank you @basbruss

**Comment by basbruss** [comment]
@schumijo Great work so far!

In the PR for the adaptive dashboard, I am utilizing the `double_tap_action` with two variables to control an `input_select`. If that gets merged it will probably give some conflicts with this PR. 
Do you have an idea to implement the needed changes by making it the default behavior for example?
```yaml
  double_tap_action:
    action: "call-service"
    service: "input_select.select_option"
    service_data:
      option: "[[[ return variables.ulm_input_select_option ]]]"
      entity_id: "[[[ return variables.ulm_input_select ]]]"
```

**Comment by schumijo** [comment]
Hi @basbruss 
Next release will be awesome with new translation engine and your adaptive dashboard !!!

Actually, in my configuration file, we can define 4 different values : none, toggle, more-info and popup 

ulm_global_config:
  variables:
    ulm_global_card_tap_action: "toggle"
    ulm_global_card_hold_action: "popup"
    ulm_global_card_double_tap_action: "more-info"
    ulm_global_icon_tap_action: "popup"
    ulm_global_icon_hold_action: "none"
    ulm_global_icon_double_tap_action: "none"
    ulm_global_name_tap_action: "more-info"
    ulm_global_name_hold_action: "toggle"
    ulm_global_name_double_tap_action: "popup"

I think we can add a fifth option for adaptive control. 
It needs some changes on each cards as I have done with popups.
But for testing purpose, I need to merge your PR with mine on my dev environment.

**Pull request merged**
