### PR TITLE
Update of card_light

### PR DESCRIPTION
**Pull request by basbruss**
Add mode switching based on `hass.themes.darkMode`.
This deprecates `variable.ulm_card_light_enable_background_color`.
Add popup fix to all areas of the card, based on #282 
Documentation still needs to be updated!

### CODE REVIEW

**Comment by CM000n** [comment]
Hi @basbruss, great work. Thanks a lot! Do you want to edit the docs yourself, or should we do it afterwards?

**Comment by basbruss** [comment]
Hi @schumijo the documentation is added in this PR

**Comment by CM000n** [comment]
I saw that you also made some changes to the popups. Is your MR meant to be complementary to @schumijo's, or does it replace it?
https://github.com/UI-Lovelace-Minimalist/UI/pull/282

**Comment by basbruss** [comment]
It is to replace it :smile:

**Pull request merged**
